# SPDX-FileCopyrightText: Copyright 2025 The SLSA Authors
# SPDX-License-Identifier: Apache-2.0
---
  
name: "Compute SLSA Source Metadata"
on:
  workflow_call:
    inputs:
      allow-merge-commits:
        type: boolean
        description: 'Experimental support for merge commits '
        required: false
        default: false

      build-from-source:
        type: boolean
        description: 'Build the sourcetool binary from source (@HEAD)'
        required: false
        default: false

      version:
        description: "sourcetool version to run"
        type: string
        default: "v0.6.2"
        required: false

jobs:
  compute_slsa_source:
    permissions:
      contents: write # needed for storing attestations in the repo
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - name: prov
      uses: slsa-framework/source-actions/slsa_with_provenance@main
      with:
        allow-merge-commits: ${{inputs.allow-merge-commits}}
        build-from-source: ${{ inputs.build-from-source }}
        version: ${{ inputs.version }}
